stages:
  - checkout
  - build
  - push
  - deploy

variables:
  DOCKER_IMAGE: 'your-dockerhub-username/your-image-name:${CI_PIPELINE_ID}'
  DOCKER_SWARM_MANAGER: 'user@swarm-manager-ip'
  SWARM_SSH_PRIVATE_KEY: $SWARM_SSH_PRIVATE_KEY
  TELEGRAM_BOT_TOKEN: 'your-telegram-bot-token'
  TELEGRAM_CHAT_ID: 'your-telegram-chat-id'

checkout:
  stage: checkout
  script:
    - git clone -b main https://gitlab.com/your-username/your-repo.git

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .

push:
  stage: push
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - echo "$SWARM_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh -o StrictHostKeyChecking=no $DOCKER_SWARM_MANAGER 'docker service update --image $DOCKER_IMAGE your_service_name'

telegram_notification:
  stage: deploy
  script:
    - curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=Build $CI_JOB_NAME finished with status: $CI_JOB_STATUS"
